### ISSUE TITLE
Website hacked

### ISSUE THREAD

**Issue by fadyscube** [ykdojo/csqa#13]

**Comment by ykdojo** [comment]
I think you’re talking about this one. I’ll look into it.

https://csqa.io/question/424

**Comment by fadyscube** [comment]
Yes I talk about this question but why I have this alert!

**Comment by eltorodev** [comment]
What's happened?

**Comment by ykdojo** [comment]
I fixed it: https://github.com/ykdojo/csqa/commit/f58a5f59d4a4118fd6934efb59e2253837890497
